### ISSUE TITLE
SSMD::strip_ssmd should remove last pause of string if there is no space after it. 

### ISSUE THREAD

**Issue by mian-bilal** [machisuji/ssmd#3]
Example:

```
SSMD::strip_ssmd "Hello ...2s World ...2s"
```

Expected result: Hello World
Actual result: "Hello World ...2s"

**Comment by machisuji** [comment]
Thanks for reporting the bug @mian-bilal. I just fixed the bug and some others I found. It's included in the latest version: 0.7.6
